/*
 * @Description:
 * @Author: Lewis
 * @Date: 2022-01-17 23:34:15
 * @LastEditTime: 2022-02-13 23:36:31
 * @LastEditors: Lewis
 */
const authActionType = {
  SET_SHOW_MODAL: "SET_SHOW_MODAL",
  SET_MODAL_TYPE: "SET_MODAL_TYPE",

  CREATE_USER_START: "CREATE_USER_START",
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILURE: "CREATE_USER_FAILURE",

  LOGIN_USER_START: "LOGIN_USER_START",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILURE: "LOGIN_USER_FAILURE",

  LOGOUT_USER_START: "LOGOUT_USER_START",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_FAILURE: "LOGOUT_USER_FAILURE",

  SET_GLOBAL_LOADING:'SET_GLOBAL_LOADING'
};

export default authActionType;
