/*
 * @Description: 
 * @Author: Lewis
 * @Date: 2022-01-09 23:13:03
 * @LastEditTime: 2022-01-25 23:03:37
 * @LastEditors: Lewis
 */
const musicActionType = {
    GET_MUSIC_TOP10_START: "GET_MUSIC_TOP10_START",
    GET_MUSIC_TOP10_SUCCESS: "GET_MUSIC_TOP10_SUCCESS",
    GET_MUSIC_TOP10_FAILURE: "GET_MUSIC_TOP10_FAILURE",

    CREATE_MUSIC_START: "CREATE_MUSIC_START",
    CREATE_MUSIC_SUCCESS: "CREATE_MUSIC_SUCCESS",
    CREATE_MUSIC_FAILURE: "CREATE_MUSIC_FAILURE",

    GET_MUSIC_BY_TYPE_START: "GET_MUSIC_BY_TYPE_START",
    GET_MUSIC_BY_TYPE_SUCCESS: "GET_MUSIC_BY_TYPE_SUCCESS",
    GET_MUSIC_BY_TYPE_FAILURE: "GET_MUSIC_BY_TYPE_FAILURE",

    FIND_MUSIC_BY_ID_START: "FIND_MUSIC_BY_ID_START",
    FIND_MUSIC_BY_ID_SUCCESS: "FIND_MUSIC_BY_ID_SUCCESS",
    FIND_MUSIC_BY_ID_FAILURE: "FIND_MUSIC_BY_ID_FAILURE",
  };
  
  export default musicActionType;