/*
 * @Description:
 * @Author: Lewis
 * @Date: 2022-01-09 23:13:03
 * @LastEditTime: 2022-02-25 00:33:27
 * @LastEditors: Lewis
 */
const musicActionType = {
  GET_MUSIC_TOP10_START: "GET_MUSIC_TOP10_START",
  GET_MUSIC_TOP10_SUCCESS: "GET_MUSIC_TOP10_SUCCESS",
  GET_MUSIC_TOP10_FAILURE: "GET_MUSIC_TOP10_FAILURE",

  CREATE_MUSIC_START: "CREATE_MUSIC_START",
  CREATE_MUSIC_SUCCESS: "CREATE_MUSIC_SUCCESS",
  CREATE_MUSIC_FAILURE: "CREATE_MUSIC_FAILURE",

  GET_MUSIC_BY_TYPE_START: "GET_MUSIC_BY_TYPE_START",
  GET_MUSIC_BY_TYPE_SUCCESS: "GET_MUSIC_BY_TYPE_SUCCESS",
  GET_MUSIC_BY_TYPE_FAILURE: "GET_MUSIC_BY_TYPE_FAILURE",

  FIND_MUSIC_BY_ID_START: "FIND_MUSIC_BY_ID_START",
  FIND_MUSIC_BY_ID_SUCCESS: "FIND_MUSIC_BY_ID_SUCCESS",
  FIND_MUSIC_BY_ID_FAILURE: "FIND_MUSIC_BY_ID_FAILURE",

  GET_MY_MUSIC_START: "GET_MY_MUSIC_START",
  GET_MY_MUSIC_SUCCESS: "GET_MY_MUSIC_SUCCESS",
  GET_MY_MUSIC_FAILURE: "GET_MY_MUSIC_FAILURE",

  SEARCH_MUSIC_START: "SEARCH_MUSIC_START",
  SEARCH_MUSIC_SUCCESS: "SEARCH_MUSIC_SUCCESS",
  SEARCH_MUSIC_FAILURE: "SEARCH_MUSIC_FAILURE",

  GET_COMMENT_START: "GET_COMMENT_START",
  GET_COMMENT_SUCCESS: "GET_COMMENT_SUCCESS",
  GET_COMMENT_FAILURE: "GET_COMMENT_FAILURE",

  SAVE_COMMENT_START: "SAVE_COMMENT_START",
  SAVE_COMMENT_SUCCESS: "SAVE_COMMENT_SUCCESS",
  SAVE_COMMENT_FAILURE: "SAVE_COMMENT_FAILURE",

  SET_COMMENT_REAL_TIME: "SET_COMMENT_REAL_TIME",
};

export default musicActionType;
